export default [
  {
    title: 'Vožnja javnim prevozom',
    color: '#5FAD9F',
    image: require('../images/djela/image_javniprevoz.png'),
    id: 'prevoz',
    aspectRatio: 1.25,
  },
  {
    title: 'Iznajmljivanje gradskog bicikla',
    color: '#91C3CA',
    image: require('../images/djela/image_gradskibicikl.png'),
    id: 'bicikl',
    aspectRatio: 1.4,
  },
  {
    title: 'Iznajmljivanje električnih skutera',
    color: '#E9B55D',
    image: require('../images/djela/image_skuter.png'),
    id: 'skuter',
    aspectRatio: 1.35,
  },
  {
    title: 'Reciklaža',
    color: '#EAA984',
    image: require('../images/djela/image_reciklaza.png'),
    id: 'reciklaza',
    aspectRatio: 1.3,
  },
  {
    title: 'Doniranje hrane azilima za životinje',
    color: '#94C176',
    image: require('../images/djela/image_hrana.png'),
    id: 'azil',
    aspectRatio: 1.2,
  },
  {
    title: 'Doniranje hrane i odjeće humanitarnim organizacijama',
    color: '#7191BB',
    image: require('../images/djela/image_hranaodjeca.png'),
    id: 'hrana',
    aspectRatio: 1.5,
  },
  {
    title: 'Podijeli mjesto dostupno za lica sa invaliditetom',
    color: '#D98585',
    image: require('../images/djela/image_licaukolicima.png'),
    id: 'invaliditet',
    aspectRatio: 1.5,
  },
  {
    title: 'Donacije domu za nezbrinutu djecu',
    color: '#BBA86C',
    image: require('../images/djela/image_nezbrinutadjeca.png'),
    id: 'djeca',
    aspectRatio: 1.3,
  },
  {
    title: 'Prijavi neizdavanje fiskalnih računa',
    color: '#EE8CEC',
    image: require('../images/djela/image_racun.png'),
    id: 'racun',
    aspectRatio: 1.25,
  },
  {
    title: 'Slanje SMSa na humanitarne brojeve',
    color: '#8BBA9E',
    image: require('../images/djela/image_sms.png'),
    id: 'sms',
    aspectRatio: 1.4,
  },
  {
    title: 'Doniranje krvi',
    color: '#61ABD5',
    image: require('../images/djela/image_doniranjekrvi.png'),
    id: 'krv',
    aspectRatio: 1.3,
  },
  {
    title: 'Glasanje',
    color: '#91A2B6',
    image: require('../images/djela/image_glasaj.png'),
    id: 'glasanje',
    aspectRatio: 1.35,
  },
  {
    title: 'Volontiranje',
    color: '#C793C5',
    image: require('../images/djela/image_volontiranje.png'),
    id: 'volontiranje',
    aspectRatio: 1.2,
  },
  {
    title: 'Parkiranje na humani parking',
    color: '#CEAB95',
    image: require('../images/djela/image_parkiranje.png'),
    id: 'parkiranje',
    aspectRatio: 1.35,
  },
  {
    title: 'Doniraj sadnicu',
    color: '#6591C9',
    image: require('../images/djela/image_sadnica.png'),
    id: 'sadnica',
    aspectRatio: 1.3,
  },
  {
    title: 'Specijalne akcije grada',
    color: '#4F814A',
    image: require('../images/djela/image_akcijegrada.png'),
    id: 'akcije',
    aspectRatio: 1.2,
  },
];
